### PR TITLE
Fix demo

### LINKED ISSUE #6: Fix demo
The demo currently doesn't work.

### PR DESCRIPTION
**Pull request by peteretelej**
Fixes demo.

- Sources API Key, username and shortcode from environment
- Removes .idea/ from git
- Refactors duplicated logic in host generation

Fixes #6

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,3 +1,3 @@
-.idea/*
+.idea/
```
Comment (chweez) [inline .gitignore]: Why remove the wildcard here?

File: demo/main.go [hunk 2]
```diff
@@ -22,24 +23,28 @@ func main() {
 
 	flag.Parse()
 	if *recipient == "" || *message == "" {
-		log.Println("please enter recipient and message")
-		os.Exit(1)
+		log.Fatal("please enter all required arguments. see --help")
+	}
+
+	if apiKey == "" || username == "" || shortcode == "" {
```
Comment (chweez) [inline demo/main.go]: Shortcode being an empty string should be allowed here. It's the default where the message is sent from "AFRICASTKNG" as the shortcode, which is set by africastalking if nothing is set.

File: demo/main.go [hunk 3]
```diff
@@ -22,24 +23,28 @@ func main() {
...
-	sendResponse, err := smsService.Send("Me4u", *recipient, *message)
+
+	sendResponse, err := smsService.Send(shortcode, *recipient, *message)
 	if err != nil {
-		fmt.Println(err)
-	} else {
-		fmt.Println(sendResponse)
+		fmt.Printf("Failed to send sms: %v", err)
 	}
+	fmt.Printf("SMS Send reponse: %v\n", sendResponse)
```
Comment (chweez) [inline demo/main.go]: You still hit the `sendResponse` even if `err!=nil`. I printed the `sendResponse` in an `else` block to avoid that same scenario

File: .gitignore (hunk 1 above)
Comment (peteretelej) [reply .gitignore]: because it's not necessary to ignore the directory, even `.idea` would suffice, but the trailing slash helps imply a directory

File: demo/main.go (hunk 3 above)
Comment (peteretelej) [reply demo/main.go]: In case of an error, this prints `SMS Send reponse: <nil>` which is still accurate. The `else` was a code smell, exiting early e.g. with `log.Fatal` was what I wanted to do at first

File: demo/main.go (hunk 2 above)
Comment (peteretelej) [reply demo/main.go]: Oh, didn't know that, will make change.

**Comment by peteretelej** [comment]
Updated PR

File: .gitignore (hunk 1 above)
Comment (chweez) [reply .gitignore]: Ok
